"""Generate the documentation's numerical summary from current JSON reports."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
v = json.loads((ROOT/'results/validation_report.json').read_text())
p = json.loads((ROOT/'results/gluon_born_report.json').read_text())
g = json.loads((ROOT/'results/gluon_born_grid_report.json').read_text())
n = sum(value == 'PASS' for value in v.values())
if n != 49 or not all(p['checks'].values()) or g['points'] != 36 or not g['all_pass']:
    raise ValueError('Reports do not contain the expected passing validations')
lines = [
    '# Generated result summary',
    '',
    'This page is generated by `scripts/update_report_summary.py` from the current JSON reports.',
    '',
    f'**All {n} exact symbolic checks pass.**',
    '',
    '| Symbolic quantity | Value |',
    '|---|---:|',
    f"| Quark catalogue entries | {len(v['quark_catalogue'])} |",
    f"| Gluon catalogue entries | {len(v['gluon_catalogue'])} |",
    '| Quark tensor-map rank | 32 (exact PASS check) |',
    '| Gluon tensor-map rank | 32 (exact PASS check) |',
    '',
    '## Reference Born point',
    '',
    '| Input | Value |', '|---|---:|',
]
for key, value in p['inputs'].items():
    lines.append(f'| `{key}` | {value:g} |')
lines.extend(['', '| Observable | Value |', '|---|---:|'])
for key, value in p['Stokes'].items():
    lines.append(f'| `{key}` | {value:.9g} |')
for i, value in enumerate(p['B_eigenvalues'], 1):
    lines.append(f'| B eigenvalue {i} | {value:.9g} |')
for key, value in p['relative_Ward_residuals'].items():
    lines.append(f'| {key} Ward residual | {value:.4g} |')
lines.append(f"| Hermiticity residual | {p['relative_Hermiticity_residual']:.4g} |")
lines.extend(['', 'B real part:', '', '```text', str(p['B_real']), '```', '',
              'B imaginary part:', '', '```text', str(p['B_imag']), '```', '',
              f"**All hard-response validation checks pass at all {g['points']} supplied grid points.**",
              '', 'These are coupling-stripped Born-level hard responses and validation diagnostics, not lithium-7 cross-section predictions.', ''])
(ROOT/'docs/generated-results.md').write_text('\n'.join(lines), encoding='utf-8')
print('Updated docs/generated-results.md from JSON reports')
